# Generated by Django 6.0.1 on 2026-01-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una carrera con este nombre.'}, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una modalidad con este nombre.'}, max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='carrera',
            table='carrera',
        ),
        migrations.AlterModelTable(
            name='modalidad',
            table='modalidad',
        ),
    ]
